name: Simple Python app pipeline

on: 
  push:
    branches: [main]
    paths:
      - 'Simple_Python_App/**'

jobs:
  build:  
    runs-on:  ubuntu-latest
    
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
  
      - name: build docker image
        run: docker build -t simple_python_app:latest -f Simple_Python_App/Dockerfile .
  
      - run: |
          docker run simple_python_app:latest
          sleep 5
          docker logs test-container
          docker stop test-container
