name: Simple Python app pipeline

on: 
  push:
    branches: [main]
    paths:
      - 'Simple_Python_App/**'
    

jobs:
  build:  
    runs-on:  ubuntu-latest
    
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
  
      - name: build docker image
        run: docker build -t simple_python_app:latest ./Simple_Python_App
        
  
      - name: Run Docker Container
        run: |
          docker run --name my-test-app --rm simple_python_app:latest
